### ISSUE TITLE
"become: yes" is missing in various places

### ISSUE THREAD

**Issue by lindt** [Icinga/ansible-playbooks#106]
Using the ansible roles without _--become_ is impossible. Many steps currently require super user privileges. Would prefer to run the ansible roles without executing everything as super user and just use super user privileges when needed.

```
- yum:
    name: icinga2
    state: present
```

## Expected Behavior

```
- yum:
    name: icinga2
    state: present
  become: yes .   # would prefer this explicit super user privileges
```

## Possible Solution

Adding `behave: yes` to places where super user privileges are required.

## Steps to Reproduce (for bugs)

Execute the roles without `--become`
