### ISSUE TITLE
add_hosts hardcodes icinga:icinga user/group but debian uses nagios:nagios

### ISSUE THREAD

**Issue by toresbe** [Icinga/ansible-playbooks#94]
I'd submit a pull request to fix this myself but I'm too unfamiliar with ansible as of now to have any confidence that I'm using the right approach to address this.

eg. icinga2-ansible/icinga2-ansible-add-hosts/tasks/main.yml:

```
- name: create Autogenerated host directory
  file:
      path: "{{ icinga2_hosts_dir }}"
      owner: **icinga**
      group: **icinga**
```

For me it was no big deal to just hardcode the other user/group, but it would be nice if this worked right out of the box.
